#this script takes the [model]_sig_genes_all_pheno.csv file generated by Manhattan_all_pheno.R and filters it for bonferroni significance, generates a [model]_bonferroni_all_pheno.csv file
library(dplyr)
library(data.table)
"%&%" = function(a,b) paste(a,b,sep="")

models<-c("PAV_filtered_rho0.1_zpval0.05","PAV_filtered_unfiltered","rho0.1_zpval0.05","unfiltered")

for (model in models){
	spred<-read.csv("PCAIRbaseline_"%&%model%&%"_sig_genes_all_pheno.csv")
	print(model)
	bonf <- 0.05/(5*28*nrow(spred))
	signif <- filter(spred,-log10(P) > -log10(bonf))
	print(bonf)
	signif <- unique(signif)  
	write.csv(signif,file="PCAIRbaseline_"%&%model%&%"_bonferroni_all_pheno.csv",quote=F,row.names=F)
}
